### ISSUE TITLE
Possible update to Minecraft version 1.21.4?

### ISSUE THREAD

**Issue by BrockBoB** [fakeneko/auto-switch-elytra#2]
Hello, I wanted to ask you if you could update the mod to Minecraft version 1.21.4, you mod is really the best one when it comes to elytra autoswitch and I really miss it.

Thank you :)

**Comment by fakeneko** [comment]
You can use the auto switch elytra 1.21.3 version on minecraft 1.21.4. And I tested today and it can run normally

**Comment by BrockBoB** [comment]
Thank you very much it works perfectly!
